Ff series relay 6
MLSTRM/relay-controller pull request #27
Opened 2021-05-03 11:52 UTC by Mrzwanzig

2021-05-03 12:07 UTC, MLSTRM requested changes

2021-05-03 12:07 UTC, MLSTRM commented on ffrelaytoolv1/TeamControl.cs
> -            vsLabelNames = new Label[context.numberOfTeams - 1];
This should probably have another option in the file as to what page we want this on

2021-05-03 12:07 UTC, MLSTRM commented on ffrelaytoolv1/TeamControl.cs
> +                    int j = Util.clamp(otherTeams[team].splitNum, context.splits.Length - (context.splitsToShow - context.splitFocusOffset), context.splitFocusOffset);
int i = Math.Max(i, Util.clamp(blah blah blah))
Either that or have more descriptive variable names :)

2021-05-03 12:07 UTC, MLSTRM commented on ffrelaytoolv1/Util.cs
> +            if (seg.TotalHours == 0)
Should probably be <= 0

2021-05-03 12:07 UTC, MLSTRM commented on ffrelaytoolv1/Util.cs
> +        public static void updateSingleDifferenceDisplay(Label label, TimeSpan seg)
Potentially should be renamed to `UpdatePositiveDifferenceDisplay`

2021-05-04 13:12 UTC, Mrzwanzig commented
Requested changes have been implemented.

2021-05-08 23:18 UTC, MLSTRM approved these changes

2021-05-08 23:19 UTC, merged